#pragma once
static const char *dir_list_html1 = ""
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=yes\">\n"
"<title>File Browser</title>\n"
"<link rel=\"icon\" type=\"image/png\" href=\"/_static_web_files/favicon.ico\"/>\n"
"<script src=\"/_static_web_files/js/jquery-3.6.0.min.js\"></script>\n"
"<script src=\"/_static_web_files/js/default.js\"></script>\n"
"<link rel=\"stylesheet\" href=\"/_static_web_files/css/default.css\">\n"
"<link rel=\"stylesheet\" href=\"/_static_web_files/css/fontawsome_all.css\">\n"
"</head>\n"
"<body>\n"
"<div class=\"container\">\n"
"<input type=\"hidden\" id=\"dirpath\" value=\"%.*s\"/>\n"
"<input type=\"hidden\" id=\"ro_flag\" value=\"%s\"/>\n"
"<input type=\"file\" id=\"uploadf\" style=\"display: none\"/>\n"
"<div class=\"row\" id=\"nav-bar\">\n"
"<p id=\"home-btn\" title=\"Home\"><a href=\"/\"><i class=\"fa fa-home fa-lg\"></i></a></p>\n"
"<p id=\"path\"></p>\n"
"<p id=\"preferences-btn\" title=\"preferences\"><a href=\"/api/preferences\"><i class=\"fa fa-wrench fa-lg\"></i></a></p>\n"
"<p id=\"logout-btn\" title=\"Logout\"><a href=\"/api/logout\"><i class=\"fa fa-sign-out-alt fa-lg\"></i></a></p>\n"
"</div>\n"
"<div id=\"table-div\">\n"
"<table cellpadding=\"0\" id=\"flist\">\n"
"<thead>\n"
"<tr>\n"
"<th onclick=\"sortTableByName();\">Name</th>\n"
"<th onclick=\"sortTableByModified();\">Modified</th>\n"
"<th onclick=\"sortTableByFileSize();\">Size</th>\n"
"</tr>\n"
"</thead>\n"
"<tbody id=\"tb\">\n"
;
