#pragma once
static const char *dir_list_html2 = ""
"</tbody></table>\n"
"</div>\n"
"<div class=\"row\" id=\"tool-bar\">\n"
"<p id=\"upload-btn\" title=\"Upload\" onclick=\"browseForFile();\"><i class=\"fa fa-upload fa-lg\"></i></p>\n"
"<p id=\"archive-btn\" title=\"Archive\" onclick=\"archive_sel();\"><i class=\"fa fa-archive fa-lg\"></i></p>\n"
"<p id=\"del-btn\" title=\"Delete\" onclick=\"delete_sel();\"><i class=\"fa fa-trash-alt fa-lg\"></i></p>\n"
"<p id=\"rename-btn\" title=\"Rename\" onclick=\"rename_sel();\"><i class=\"fa fa-pencil-alt fa-lg\"></i></p>\n"
"<p id=\"copy-btn\" title=\"Copy\" onclick=\"copy_sel();\"><i class=\"fa fa-copy fa-lg\"></i></p>\n"
"<p id=\"cut-btn\" title=\"Cut\" onclick=\"cut_sel();\"><i class=\"fa fa-cut fa-lg\"></i></p>\n"
"<p id=\"paste-btn\" title=\"Paste\" onclick=\"paste_sel();\"><i class=\"fa fa-clipboard fa-lg\"></i></p>\n"
"<p id=\"share-btn\" title=\"Share\" onclick=\"share_sel();\"><i class=\"fa fa-share-alt fa-lg\"></i></p>\n"
"</div>\n"
"</div>\n"
"</body>\n"
"<script src=\"/_static_web_files/js/popup.js\"></script>\n"
"<script src=\"/_static_web_files/js/selection.js\"></script>\n"
"<script src=\"/_static_web_files/js/sort-table.js\"></script>\n"
"</html>\n"
;
