#pragma once
static const char *login_html = ""
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<title>File Server login</title>\n"
"<meta charset=\"utf-8\" />\n"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"<link rel=\"icon\" type=\"image/png\" href=\"/_static_web_files/favicon.ico\"/>\n"
"<link rel=\"stylesheet\" href=\"/_static_web_files/css/default.css\">\n"
"</head>\n"
"<body>\n"
"<div class=\"rounded border bg-light\" id=\"login-div\">\n"
"<div class=\"margin-div\">\n"
"<h1 class=\"text-muted\">Login</h1>\n"
"<input type=\"username\" placeholder=\"User Name\" id=\"username\" autofocus>\n"
"<input type=\"password\" placeholder=\"Password\" id=\"password\">\n"
"<button onclick=\"login();\"> Login </button>\n"
"</div>\n"
"</div>\n"
"</body>\n"
"<script src=\"/_static_web_files/js/jquery-3.6.0.min.js\"></script>\n"
"<script src=\"/_static_web_files/js/popup.js\"></script>\n"
"<script src=\"/_static_web_files/js/login.js\"></script>\n"
"</html>\n"
;
