#pragma once
static const char *logout_html = ""
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<title>File Server logout</title>\n"
"</head>\n"
"<body>\n"
"<h1 style=\"color: red;margin: 5em auto;width: 13em;\">Signed out. Redirecting...</h1>\n"
"</body>\n"
"<script>\n"
"window.onload = function() {\n"
"setTimeout(function(){ window.location.replace('/'); }, 1000);\n"
"}\n"
"</script>\n"
"</html>\n"
;
