#pragma once
static const char *preferences_html = ""
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<title>FS Preferences</title>\n"
"<meta charset=\"utf-8\" />\n"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"<link rel=\"icon\" type=\"image/png\" href=\"/_static_web_files/favicon.ico\"/>\n"
"<link rel=\"stylesheet\" href=\"/_static_web_files/css/default.css\">\n"
"<link rel=\"stylesheet\" href=\"/_static_web_files/css/fontawsome_all.css\">\n"
"</head>\n"
"<body>\n"
"<div class=\"container\">\n"
"<div class=\"row\" id=\"nav-bar\">\n"
"<p id=\"home-btn\" title=\"Home\"><a href=\"/\"><i class=\"fa fa-home fa-lg\"></i></a></p>\n"
"<p id=\"update-btn\" title=\"Check for updates\" onclick=\"chk_update();\"><i class=\"fa fa-calendar-check fa-lg\"></i></p>\n"
"<p id=\"pwr-btn\" title=\"Restart computer\"><a href=\"/api/restart\"><i class=\"fa fa-power-off fa-lg\"></i></p>\n"
"<p id=\"logout-btn\" title=\"Logout\"><a href=\"/api/logout\"><i class=\"fa fa-sign-out-alt fa-lg\"></i></a></p>\n"
"</div>\n"
"<div class=\"rounded border bg-light\" id=\"preferences-div\">\n"
"<div class=\"margin-div\">\n"
"<h1 class=\"text-muted\">Preferences</h1>\n"
"\n"
"<label for=\"username\">User Name</label>\n"
"<input type=\"username\" id=\"username\">\n"
"<label for=\"new_pass\">New password</label>\n"
"<input type=\"password\" id=\"new_pass\" name=\"new_pass\">\n"
"<label for=\"confirm_pass\">Confirm new password</label>\n"
"<input type=\"password\" placeholder=\"Confirm new password\" id=\"confirm_pass\" name=\"confirm_pass\">\n"
"<input type=\"checkbox\" name=\"require_login\" id=\"require_login\">\n"
"<label for=\"require_login\">Require login in local network</label>\n"
"<i class=\"fa fa-question-circle fa-lg\" onclick=\"popup_description(event,\n"
"'If unchecked no login will be required on local network. If accessed from outside of local network, ' +\n"
"'the login will still be required.');\"></i>\n"
"<br><hr><br>\n"
"<label for=\"subdomain\">Select subdomain for external access</label>\n"
"<i class=\"fa fa-question-circle fa-lg\" onclick=\"popup_description(event,\n"
"'Prefix to the external web address to avoid assigning a random one at every restart.' +\n"
"' This way the shared items will always be available via same shared link.');\"></i>\n"
"<input type=\"text\" id=\"subdomain\">\n"
"<button onclick=\"save_prefs();\">Save</button>\n"
"</div>\n"
"</div>\n"
"</div>\n"
"</body>\n"
"<script src=\"/_static_web_files/js/jquery-3.6.0.min.js\"></script>\n"
"<script src=\"/_static_web_files/js/popup.js\"></script>\n"
"<script src=\"/_static_web_files/js/preferences.js\"></script>\n"
"</html>\n"
;
