#pragma once
static const char *share_list_html = ""
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=yes\">\n"
"<title>File Browser</title>\n"
"<link rel=\"icon\" type=\"image/png\" href=\"/_static_web_files/favicon.ico\"/>\n"
"<script src=\"/_static_web_files/js/jquery-3.6.0.min.js\"></script>\n"
"<link rel=\"stylesheet\" href=\"/_static_web_files/css/default.css\">\n"
"<link rel=\"stylesheet\" href=\"/_static_web_files/css/fontawsome_all.css\">\n"
"</head>\n"
"<body>\n"
"<div class=\"container\">\n"
"<div class=\"row\" id=\"nav-bar\">\n"
"<p id=\"home-btn\" title=\"Home\"><a href=\"/\"><i class=\"fa fa-home fa-lg\"></i></a></p>\n"
"</div>\n"
"<div id=\"table-div\">\n"
"<table cellpadding=\"0\" id=\"sharelist\">\n"
"<thead>\n"
"<tr>\n"
"<th><i id=\"select-all-btn\" title=\"Select/de-select all.\" onclick=\"select_all();\" class=\"fa fa-check-square fa-lg\"></i></th>\n"
"<th>Shared items path</th>\n"
"</tr>\n"
"</thead>\n"
"</table>\n"
"</div>\n"
"<div class=\"row\" id=\"tool-bar\">\n"
"<p id=\"del-btn\" title=\"Delete\" onclick=\"delete_sel();\"><i class=\"fa fa-trash-alt fa-lg\"></i></p>\n"
"</div>\n"
"</div>\n"
"</body>\n"
"<script src=\"/_static_web_files/js/popup.js\"></script>\n"
"<script src=\"/_static_web_files/js/shared.js\"></script>\n"
"</html>\n"
;
